openapi: 3.0.1
info:
  title: Facturas de Contingencia
  version: 1.0.0
servers:
  - url: http://localhost/apidian2021/public/api
    description: Servidor Local
paths:
  /ubl2.1/invoice-contingency:
    post:
      tags:
        - Facturas de Contingencia
      summary: Enviar Factura de Contingencia
      description: |
        Endpoint para enviar facturas de contingencia.
        
        Aplica la misma documentacion que el PRIMER ENVIO DE FACTURA de la seccion 02 - PRIMEROS ENVIOS.
        
        Este ejemplo ilustra como se debe utilizar la API para enviar una factura de contingencia, se debe especificar los datos de la factura a la cual se hace referencia en los campos AdditionalDocumentReferenceID, AdditionalDocumentReferenceDate y AdditionalDocumentReferenceTypeDocument.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
            examples:
              Contingencia:
                summary: Factura de Contingencia
                description: Ejemplo de factura de contingencia con referencia a documento adicional.
                value:
                  number: 990000963
                  type_document_id: 3
                  AdditionalDocumentReferenceID: "CN36"
                  AdditionalDocumentReferenceDate: "2024-03-17"
                  AdditionalDocumentReferenceTypeDocument: "01"
                  date: "2024-03-18"
                  time: "06:08:12"
                  customer:
                    identification_number: 89008003
                    name: "ALEXANDER OBANDO LONDONO"
                    phone: "3103891693"
                    address: "BRR LIMONAR MZ 6 CS 3 ET 1"
                    email: "alexander_obando@hotmail.com"
                    merchant_registration: "0000-00"
                    type_document_identification_id: 3
                    type_organization_id: 2
                    municipality_id: 149
                    type_regime_id: 2
                  payment_form:
                    payment_form_id: 1
                    payment_method_id: 10
                    payment_due_date: "2024-03-18"
                    duration_measure: "0"
                  allowance_charges:
                    - discount_id: 1
                      charge_indicator: false
                      allowance_charge_reason: "DESCUENTO GENERAL"
                      amount: "0.00"
                      base_amount: "840336.13"
                  legal_monetary_totals:
                    line_extension_amount: "840336.13"
                    tax_exclusive_amount: "840336.13"
                    tax_inclusive_amount: "1000000.00"
                    allowance_total_amount: "0.00"
                    charge_total_amount: "0.00"
                    payable_amount: "1000000.00"
                  tax_totals:
                    - tax_id: 1
                      tax_amount: "159663.86"
                      percent: "19"
                      taxable_amount: "840336.13"
                  invoice_lines:
                    - unit_measure_id: 70
                      invoiced_quantity: "1"
                      line_extension_amount: "840336.13"
                      free_of_charge_indicator: false
                      allowance_charges:
                        - charge_indicator: false
                          allowance_charge_reason: "DESCUENTO GENERAL"
                          amount: "0.00"
                          base_amount: "1000000.00"
                      tax_totals:
                        - tax_id: 1
                          tax_amount: "159663.86"
                          taxable_amount: "840336.13"
                          percent: "19.00"
                      description: "COMISION POR SERVICIOS"
                      code: "COMISION"
                      type_item_identification_id: 4
                      price_amount: "840336.13"
                      base_quantity: "1"
      responses:
        '200':
          description: Factura de contingencia procesada correctamente
          content:
            application/json:
              schema:
                type: object
