openapi: 3.0.1
info:
  title: Facturas de Exportación
  version: 1.0.0
servers:
  - url: http://localhost/apidian2021/public/api
    description: Servidor Local
paths:
  /ubl2.1/invoice-export:
    post:
      tags:
        - Facturas de Exportación
      summary: Enviar Factura de Exportación
      description: |
        Endpoint para enviar facturas de exportación.
        
        Aplica la misma documentacion que el PRIMER ENVIO DE FACTURA de la seccion 02 - PRIMEROS ENVIOS.
        
        Este ejemplo ilustra como se debe utilizar la API para enviar una factura de exportacion.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
            examples:
              Exportacion:
                summary: Factura de Exportación
                description: Ejemplo de factura de exportación con datos de transporte y entrega.
                value:
                  number: 990000965
                  type_document_id: 2
                  date: "2024-03-18"
                  time: "04:25:44"
                  notes: "SIN OBSERVACIONES"
                  sendmail: true
                  resolution_number: "18760000001"
                  prefix: "SETP"
                  k_supplement:
                    responsible_incharge: "JACK TORRANCE"
                    departure_place: "PEREIRA"
                    conveyance: "AVION"
                    transport_document_type: "MATRICULA"
                    transport_document_number: "HK-45089632"
                    transporter_processor: "AVIANCA"
                    merchandise_origin_country: "COLOMBIA"
                    destination: "MIAMI"
                    payment_means: "CONTADO"
                    insurance_carrier: "SURAMERICANA SEGUROS"
                    observations: "NINGUNA"
                    FctConvCop: "3890"
                    MonedaCop: "USD"
                    SubTotalCop: "200.00"
                    DescuentoDetalleCop: "0.00"
                    RecargoDetalleCop: "0.00"
                    TotalBrutoFacturaCop: "200.00"
                    TotIvaCop: "38.00"
                    TotIncCop: "0.00"
                    TotBolCop: "0.00"
                    ImpOtroCop: "0.00"
                    MntImpCop: "38.00"
                    TotalNetoFacturaCop: "238.00"
                    MntDctoCop: "0.00"
                    MntRcgoCop: "0.00"
                    VlrPagarCop: "238.00"
                    ReteFueCop: "0.00"
                    ReteIvaCop: "0.00"
                    ReteIcaCop: "0.00"
                    TotAnticiposCop: "0.00"
                  customer:
                    identification_number: "FR42128XD090"
                    name: "BLANCA NUBIA ALVAREZ ALZATE "
                    phone: "3148931130"
                    address: "CR 14 BIS 31 B 37 BRR SAN NICOLAS"
                    email: "blancanubiaa@hotmail.com"
                    merchant_registration: "0000-00"
                    type_document_identification_id: 8
                    type_organization_id: 2
                    country_id: 65
                    municipality_name: "MIAMI"
                    state_name: "FLORIDA"
                    type_liability_id: 117
                    type_regime_id: 2
                  deliveryterms:
                    special_terms: "COSTO SEGURO Y FLETE"
                    loss_risk_responsibility_code: "CIF"
                    loss_risk: "COSTO SEGURO Y FLETE"
                  payment_form:
                    payment_form_id: 2
                    payment_method_id: 10
                    payment_due_date: "2024-04-18"
                    duration_measure: "30"
                  allowance_charges:
                    - discount_id: 10
                      charge_indicator: false
                      allowance_charge_reason: "DESCUENTO GENERAL"
                      amount: "0.00"
                      base_amount: "15840.00"
                    - charge_indicator: true
                      allowance_charge_reason: "CARGO POR FLETES/FREIGHT CHARGE"
                      amount: "200.00"
                      base_amount: "15840.00"
                  legal_monetary_totals:
                    line_extension_amount: "15840.00"
                    tax_exclusive_amount: "15840.00"
                    tax_inclusive_amount: "15840.00"
                    allowance_total_amount: "0.00"
                    charge_total_amount: "200.00"
                    payable_amount: "16040.00"
                  tax_totals:
                    - tax_id: 1
                      tax_amount: "0.00"
                      percent: "0"
                      taxable_amount: "15840.00"
                  invoice_lines:
                    - unit_measure_id: 70
                      invoiced_quantity: "5.00"
                      line_extension_amount: "4950.00"
                      free_of_charge_indicator: false
                      allowance_charges:
                        - charge_indicator: false
                          allowance_charge_reason: "DESCUENTO GENERAL"
                          amount: "0.00"
                          base_amount: "4950.00"
                      tax_totals:
                        - tax_id: 1
                          tax_amount: "0.00"
                          taxable_amount: "4950.00"
                          percent: "0.00"
                      description: "LEGGINS DE DAMA REF 1032"
                      brandname: "FULLFIT"
                      modelname: "1032"
                      code: "1032"
                      type_item_identification_id: 4
                      price_amount: "990.00"
                      base_quantity: "5.00"
                    - unit_measure_id: 70
                      invoiced_quantity: "6.00"
                      line_extension_amount: "5940.00"
                      free_of_charge_indicator: false
                      allowance_charges:
                        - charge_indicator: false
                          allowance_charge_reason: "DESCUENTO GENERAL"
                          amount: "0.00"
                          base_amount: "5940.00"
                      tax_totals:
                        - tax_id: 1
                          tax_amount: "0.00"
                          taxable_amount: "5940.00"
                          percent: "0.00"
                      description: "LEGGINS DE DAMA REF 1087"
                      brandname: "FULLFIT"
                      modelname: "1087"
                      code: "1087"
                      type_item_identification_id: 4
                      price_amount: "990.00"
                      base_quantity: "6.00"
                    - unit_measure_id: 70
                      invoiced_quantity: "5.00"
                      line_extension_amount: "4950.00"
                      free_of_charge_indicator: false
                      allowance_charges:
                        - charge_indicator: false
                          allowance_charge_reason: "DESCUENTO GENERAL"
                          amount: "0.00"
                          base_amount: "4950.00"
                      tax_totals:
                        - tax_id: 1
                          tax_amount: "0.00"
                          taxable_amount: "4950.00"
                          percent: "0.00"
                      description: "LEGGINS DE DAMA REF 1088"
                      brandname: "FULLFIT"
                      modelname: "1088"
                      code: "1088"
                      type_item_identification_id: 4
                      price_amount: "990.00"
                      base_quantity: "5.00"
      responses:
        '200':
          description: Factura de exportación procesada correctamente
          content:
            application/json:
              schema:
                type: object
