openapi: 3.0.1
info:
  title: Facturas Mandato
  version: 1.0.0
servers:
  - url: http://localhost/apidian2021/public/api
    description: Servidor Local
paths:
  /ubl2.1/invoice-mandate:
    post:
      tags:
        - Facturas Mandato
      summary: Enviar Factura Mandato
      description: |
        Endpoint para enviar facturas tipo Mandato.
        
        Aplica la misma documentacion que el PRIMER ENVIO DE FACTURA de la seccion 02 - PRIMEROS ENVIOS.
        
        Este ejemplo ilustra como se debe utilizar la API para enviar una factura tipo MANDATO, este tipo de facturas se utiliza mucho en inmobiliarias, donde el valor del arrendamiento de un bien se recibe a nombre de un tercero, este tercero se especifica en los campos agentparty y agentparty_dv.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
            examples:
              Mandato:
                summary: Factura Mandato
                description: Ejemplo de factura de mandato con campos de tercero (agentparty).
                value:
                  type_document_id: 1
                  number: 990070004
                  dv: 2
                  date: "2025-05-05"
                  time: "06:44:45"
                  resolution_number: "18760000001"
                  prefix: "SETP"
                  notes: "SIN OBSERVACIONES"
                  customer:
                    identification_number: 89008003
                    dv: 2
                    name: "ALEXANDER OBANDO LONDONO"
                    phone: "3103891693"
                    address: "BRR LIMONAR MZ 6 CS 3 ET 1"
                    email: "alexander_obando@hotmail.com"
                    merchant_registration: "0000-00"
                    type_document_identification_id: 6
                    type_organization_id: 2
                    municipality_id: 149
                    type_regime_id: 2
                  payment_form:
                    payment_form_id: 1
                    payment_method_id: 10
                    payment_due_date: "2025-05-05"
                    duration_measure: "0"
                  allowance_charges:
                    - discount_id: 1
                      charge_indicator: false
                      allowance_charge_reason: "DESCUENTO GENERAL"
                      amount: "0.00"
                      base_amount: "1704201.68"
                  legal_monetary_totals:
                    line_extension_amount: "1704201.68"
                    tax_exclusive_amount: "1704201.68"
                    tax_inclusive_amount: "1800000.00"
                    allowance_total_amount: "0.00"
                    charge_total_amount: "0.00"
                    payable_amount: "1800000.00"
                  tax_totals:
                    - tax_id: 1
                      tax_amount: "0.00"
                      percent: "0"
                      taxable_amount: "1200000.00"
                    - tax_id: 1
                      tax_amount: "95798.32"
                      percent: "19"
                      taxable_amount: "504201.68"
                  invoice_lines:
                    - unit_measure_id: 70
                      invoiced_quantity: "1"
                      line_extension_amount: "600000.00"
                      free_of_charge_indicator: false
                      allowance_charges:
                        - charge_indicator: false
                          allowance_charge_reason: "DESCUENTO GENERAL"
                          amount: "0.00"
                          base_amount: "600000.00"
                      tax_totals:
                        - tax_id: 1
                          tax_amount: "0.00"
                          taxable_amount: "600000.00"
                          percent: "0.00"
                      description: "PRUEBA MANDATO"
                      code: "PRUEBA1"
                      type_item_identification_id: 4
                      price_amount: "600000.00"
                      base_quantity: "1"
                    - unit_measure_id: 70
                      invoiced_quantity: "1"
                      line_extension_amount: "600000.00"
                      free_of_charge_indicator: false
                      allowance_charges:
                        - charge_indicator: false
                          allowance_charge_reason: "DESCUENTO GENERAL"
                          amount: "0.00"
                          base_amount: "600000.00"
                      tax_totals:
                        - tax_id: 1
                          tax_amount: "0.00"
                          taxable_amount: "600000.00"
                          percent: "0.00"
                      description: "PRUEBA MANDATO"
                      code: "PRUEBA2"
                      type_item_identification_id: 4
                      price_amount: "600000.00"
                      base_quantity: "1"
                    - unit_measure_id: 70
                      invoiced_quantity: "1"
                      line_extension_amount: "504201.68"
                      free_of_charge_indicator: false
                      allowance_charges:
                        - charge_indicator: false
                          allowance_charge_reason: "DESCUENTO GENERAL"
                          amount: "0.00"
                          base_amount: "600000.00"
                      tax_totals:
                        - tax_id: 1
                          tax_amount: "95798.32"
                          taxable_amount: "504201.68"
                          percent: "19.00"
                      description: "PRUEBA MANDATO"
                      agentparty: 900468658
                      agentparty_dv: 1
                      code: "PRUEBA3"
                      type_item_identification_id: 4
                      price_amount: "504201.68"
                      base_quantity: "1"
      responses:
        '200':
          description: Factura Mandato procesada correctamente
          content:
            application/json:
              schema:
                type: object
