openapi: 3.0.1
info:
  title: Facturas de Transporte
  version: 1.0.0
servers:
  - url: http://localhost/apidian2021/public/api
    description: Servidor Local
paths:
  /ubl2.1/invoice-transport:
    post:
      tags:
        - Facturas de Transporte
      summary: Enviar Factura de Transporte
      description: |
        Endpoint para enviar facturas de transporte.
        
        Aplica la misma documentacion que el PRIMER ENVIO DE FACTURA de la seccion 02 - PRIMEROS ENVIOS.
        
        Este ejemplo ilustra como se debe utilizar la API para enviar una factura de transporte, la cual incluye datos especificos del RNDC (Registro Nacional de Despachos de Carga) en las lineas de la factura.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
            examples:
              Transporte:
                summary: Factura de Transporte
                description: Ejemplo de factura de transporte con campos RNDC.
                value:
                  number: 991500412
                  dv: 2
                  type_document_id: 1
                  date: "2023-10-25"
                  time: "06:44:45"
                  resolution_number: "18760000001"
                  prefix: "SETP"
                  notes: "SIN OBSERVACIONES"
                  customer:
                    identification_number: 89008003
                    dv: 2
                    name: "ALEXANDER OBANDO LONDONO"
                    phone: "3103891693"
                    address: "BRR LIMONAR MZ 6 CS 3 ET 1"
                    email: "alexander_obando@hotmail.com"
                    merchant_registration: "0000-00"
                    type_document_identification_id: 6
                    type_organization_id: 2
                    municipality_id: 149
                    type_regime_id: 2
                  payment_form:
                    payment_form_id: 1
                    payment_method_id: 10
                    payment_due_date: "2023-10-25"
                    duration_measure: "0"
                  allowance_charges:
                    - discount_id: 1
                      charge_indicator: false
                      allowance_charge_reason: "DESCUENTO GENERAL"
                      amount: "0.00"
                      base_amount: "1704201.68"
                  legal_monetary_totals:
                    line_extension_amount: "1704201.68"
                    tax_exclusive_amount: "1704201.68"
                    tax_inclusive_amount: "1800000.00"
                    allowance_total_amount: "0.00"
                    charge_total_amount: "0.00"
                    payable_amount: "1800000.00"
                  tax_totals:
                    - tax_id: 1
                      tax_amount: "0.00"
                      percent: "0"
                      taxable_amount: "1200000.00"
                    - tax_id: 1
                      tax_amount: "95798.32"
                      percent: "19"
                      taxable_amount: "504201.68"
                  invoice_lines:
                    - is_RNDC: true
                      RNDC_consignment_number: "95000912001"
                      internal_consignment_number: "REM000001"
                      value_consignment: "600000"
                      unit_measure_consignment_id: 767
                      quantity_consignment: "200.00"
                      unit_measure_id: 70
                      invoiced_quantity: "1"
                      line_extension_amount: "600000.00"
                      free_of_charge_indicator: false
                      allowance_charges:
                        - charge_indicator: false
                          allowance_charge_reason: "DESCUENTO GENERAL"
                          amount: "0.00"
                          base_amount: "600000.00"
                      tax_totals:
                        - tax_id: 1
                          tax_amount: "0.00"
                          taxable_amount: "600000.00"
                          percent: "0.00"
                      description: "PRUEBA TRANSPORTE"
                      code: "PRUEBA1"
                      type_item_identification_id: 4
                      price_amount: "600000.00"
                      base_quantity: "1"
                    - is_RNDC: false
                      unit_measure_id: 70
                      invoiced_quantity: "1"
                      line_extension_amount: "600000.00"
                      free_of_charge_indicator: false
                      allowance_charges:
                        - charge_indicator: false
                          allowance_charge_reason: "DESCUENTO GENERAL"
                          amount: "0.00"
                          base_amount: "600000.00"
                      tax_totals:
                        - tax_id: 1
                          tax_amount: "0.00"
                          taxable_amount: "600000.00"
                          percent: "0.00"
                      description: "PRUEBA TRANSPORTE"
                      code: "PRUEBA2"
                      type_item_identification_id: 4
                      price_amount: "600000.00"
                      base_quantity: "1"
                    - is_RNDC: false
                      unit_measure_id: 70
                      invoiced_quantity: "1"
                      line_extension_amount: "504201.68"
                      free_of_charge_indicator: false
                      allowance_charges:
                        - charge_indicator: false
                          allowance_charge_reason: "DESCUENTO GENERAL"
                          amount: "0.00"
                          base_amount: "600000.00"
                      tax_totals:
                        - tax_id: 1
                          tax_amount: "95798.32"
                          taxable_amount: "504201.68"
                          percent: "19.00"
                      description: "PRUEBA TRANSPORTE"
                      code: "PRUEBA3"
                      type_item_identification_id: 4
                      price_amount: "504201.68"
                      base_quantity: "1"
      responses:
        '200':
          description: Factura de transporte procesada correctamente
          content:
            application/json:
              schema:
                type: object
