openapi: 3.0.0
info:
  title: Documento Equivalente - POS
  version: 1.0.0
servers:
  - url: https://{url_base}/api
    variables:
      url_base:
        default: buho.fastura.uio.la
        description: Base URL of the API

paths:
  /ubl2.1/eqdoc:
    post:
      summary: Enviar Documento Equivalente (POS)
      description: |
        Envía un documento equivalente POS electrónico.
        
      tags:
        - Documento Equivalente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './eqdocs-component.yaml#/components/schemas/EqDocGeneral'
      responses:
        '200':
          description: Documento equivalente enviado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                   type: string
                  ResponseDian:
                    type: object
                  zipinvoicexml:
                    type: string
        '422':
          description: Error de validación
