openapi: 3.0.0
info:
  title: Consumidor Final
  version: 1.0.0
servers:
  - url: https://{url_base}/api
    variables:
      url_base:
        default: buho.fastura.uio.la
        description: Base URL of the API

paths:
  /ubl2.1/invoice?case=sendinvoice-testsetid-consumidor-final:
    post:
      summary: SendInvoice-TestSetId Consumidor Final
      description: |
        ENVIO DE FACTURA A CONSUMIDOR FINAL (Cuantías Menores).

        - Aplica la misma documentación que el PRIMER ENVIO DE FACTURA de la sección 02 - PRIMEROS ENVIOS.
        - Se usa el `222222222222` como identificación para el consumidor final o cuantías menores.
      tags:
        - Consumidor Final
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                number: 990000000
                type_document_id: 1
                date: "2021-08-17"
                time: "04:08:12"
                resolution_number: "18760000001"
                prefix: "SETP"
                sendmail: true
                customer:
                  identification_number: 222222222222
                  dv: 4
                  name: "CONSUMIDOR FINAL"
                  phone: "3103891693"
                  address: "CLL 4 NRO 33-90"
                  email: "alexanderobandolondono@gmail.com"
                  merchant_registration: "0000000-00"
                  type_document_identification_id: 3
                  type_organization_id: 2
                  municipality_id: 822
                  type_regime_id: 2
                payment_form:
                  payment_form_id: 1
                  payment_method_id: 10
                  payment_due_date: "2021-08-17"
                  duration_measure: "0"
                legal_monetary_totals:
                  line_extension_amount: "100.00"
                  tax_exclusive_amount: "100.00"
                  tax_inclusive_amount: "100.00"
                  allowance_total_amount: "0.00"
                  charge_total_amount: "0.00"
                  payable_amount: "100.00"
                tax_totals:
                  - tax_id: 1
                    tax_amount: "0.00"
                    percent: "0"
                    taxable_amount: "100.00"
                invoice_lines:
                  - unit_measure_id: 70
                    invoiced_quantity: "1"
                    line_extension_amount: "100.00"
                    free_of_charge_indicator: false
                    tax_totals:
                      - tax_id: 1
                        tax_amount: "0.00"
                        taxable_amount: "100.00"
                        percent: "0.00"
                    description: "COMISION POR SERVICIOS"
                    code: "COMISION"
                    type_item_identification_id: 4
                    price_amount: "100.00"
                    base_quantity: "1"
      responses:
        '200':
          description: Successful operation
