openapi: 3.0.0
info:
  title: Documento Soporte - Nota de Ajuste
  version: 1.0.0
servers:
  - url: https://{url_base}/api
    variables:
      url_base:
        default: buho.fastura.uio.la
        description: Base URL of the API

paths:
  /ubl2.1/support-document-adjust-note:
    post:
      summary: Enviar Nota de Ajuste a Documento Soporte
      description: |
        Envía una nota de ajuste para un documento soporte previamente emitido.
        
        - Debe referenciar el documento soporte original en `billing_reference`.
      tags:
        - Documento Soporte
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './support-doc-component.yaml#/components/schemas/SupportDocAdjust'
      responses:
        '200':
          description: Nota de ajuste enviada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                   type: string
                  ResponseDian:
                    type: object
                  zipinvoicexml:
                    type: string
        '422':
          description: Error de validación
