openapi: 3.0.0
info:
  title: Nomina Electronica - Nota de Ajuste
  version: 1.0.0
servers:
  - url: https://{url_base}/api
    variables:
      url_base:
        default: buho.fastura.uio.la
        description: Base URL of the API

paths:
  /ubl2.1/payroll-adjust-note/{testSetId}:
    post:
      summary: Enviar Nota de Ajuste de Nómina
      description: |
        Envía una nota de ajuste para una nómina electrónica previamente emitida.
        
        - Se usa para corregir o eliminar una nómina anterior.
        - Requiere referenciar la nómina predecesora en `predecessor`.
      tags:
        - Nomina
      parameters:
        - in: path
          name: testSetId
          schema:
            type: string
          required: true
          description: ID del Set de Pruebas.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './payroll-component.yaml#/components/schemas/PayrollAdjust'
      responses:
        '200':
          description: Nota de ajuste enviada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                   type: string
                  ResponseDian:
                    type: object
                  zippayrollxml:
                    type: string
        '422':
          description: Error de validación
