openapi: 3.0.0
info:
  title: Factura Electrónica - Nota Crédito
  version: 1.0.0
servers:
  - url: https://{url_base}/api
    variables:
      url_base:
        default: buho.fastura.uio.la
        description: Base URL of the API

paths:
  /ubl2.1/credit-note:
    post:
      summary: Enviar Nota Crédito
      description: |
        Envía una nota crédito electrónica asociada a una factura previa.
        
        - Requiere referenciar la factura original en `billing_reference`.
        - Permite anulación o corrección de valores.
      tags:
        - Nota Credito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './credit-note-component.yaml#/components/schemas/CreditNoteGeneral'
      responses:
        '200':
          description: Nota crédito procesada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  ResponseDian:
                    type: object
                  zipinvoicexml:
                    type: string
        '422':
          description: Error de validación
