openapi: 3.0.0
info:
  title: FacturaLatam ApiDianV2.1 - Colombia
  description: Servicios disponibles del proyecto APIDIAN de Facturalatam
  version: 1.0.0
servers:
  - url: http://buho.fastura.uio.la/api
    description: Servidor Principal
paths:
  /ubl2.1/config/{nit}/{dv}:
    $ref: './01-ConfiguracionesBasicas/01a-configuracion-empresa.yaml#/paths/~1ubl2.1~1config~1{nit}~1{dv}'
  /ubl2.1/config/certificate:
    $ref: './01-ConfiguracionesBasicas/01a-configuracion-empresa.yaml#/paths/~1ubl2.1~1config~1certificate'
  /ubl2.1/config/software:
    $ref: './01-ConfiguracionesBasicas/01b-configurar-factura-electronica/01b-configurar-software.yaml#/paths/~1ubl2.1~1config~1software'
  /ubl2.1/config/softwarepayroll:
    $ref: './01-ConfiguracionesBasicas/01c-configurar-nominas/01c-configurar-software-nomina.yaml#/paths/~1ubl2.1~1config~1softwarepayroll'
  /ubl2.1/config/softwaresupportdocument:
    $ref: './01-ConfiguracionesBasicas/01d-configurar-documentos-soporte/01d-configurar-software-ds.yaml#/paths/~1ubl2.1~1config~1softwaresupportdocument'
  /ubl2.1/config/softwareeqdocs:
    $ref: './01-ConfiguracionesBasicas/01e-documentos-equivalentes/01e-configurar-software-eqdocs.yaml#/paths/~1ubl2.1~1config~1softwareeqdocs'
  /ubl2.1/config/resolution:
    $ref: './01-ConfiguracionesBasicas/config-resolution.yaml#/paths/~1ubl2.1~1config~1resolution'
  /ubl2.1/invoice:
    $ref: './02-PrimerosEnvios/02a-factura/invoice.yaml#/paths/~1ubl2.1~1invoice'
  /ubl2.1/invoice/{testSetId}:
    $ref: './02-PrimerosEnvios/02a-factura/invoice.yaml#/paths/~1ubl2.1~1invoice~1{testSetId}'
  /ubl2.1/credit-note:
    $ref: './02-PrimerosEnvios/02b-nota-credito/credit-note.yaml#/paths/~1ubl2.1~1credit-note'
  /ubl2.1/debit-note:
    $ref: './02-PrimerosEnvios/02c-nota-debito/debit-note.yaml#/paths/~1ubl2.1~1debit-note'
  /ubl2.1/payroll/{testSetId}:
    $ref: './02-PrimerosEnvios/02d-nomina/payroll.yaml#/paths/~1ubl2.1~1payroll~1{testSetId}'
  /ubl2.1/payroll-adjust-note/{testSetId}:
    $ref: './02-PrimerosEnvios/02d-nomina/payroll-adjust-note.yaml#/paths/~1ubl2.1~1payroll-adjust-note~1{testSetId}'
  /ubl2.1/support-document:
    $ref: './02-PrimerosEnvios/02e-documento-soporte/support-doc.yaml#/paths/~1ubl2.1~1support-document'
  /ubl2.1/support-document-adjust-note:
    $ref: './02-PrimerosEnvios/02e-documento-soporte/support-doc-adjust.yaml#/paths/~1ubl2.1~1support-document-adjust-note'
  /ubl2.1/eqdoc:
    $ref: './02-PrimerosEnvios/02f-documentos-equivalentes/eqdocs.yaml#/paths/~1ubl2.1~1eqdoc'
  /ubl2.1/status/zip/{zipKey}:
    $ref: './03-ConsultasDeEstado/03-consultas-estado/consultas.yaml#/paths/~1ubl2.1~1status~1zip~1{zipKey}'
  /ubl2.1/status/document/{uuid}:
    $ref: './03-ConsultasDeEstado/03-consultas-estado/consultas.yaml#/paths/~1ubl2.1~1status~1document~1{uuid}'
  /ubl2.1/status/events-document/{uuid}:
    $ref: './03-ConsultasDeEstado/03-consultas-estado/consultas.yaml#/paths/~1ubl2.1~1status~1events-document~1{uuid}'
  /ubl2.1/invoice?case=sendinvoice-testsetid-order-reference:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-order-reference'
  /ubl2.1/invoice?case=sendinvoice-testsetid-varias-tarifas-y-descuentos:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-varias-tarifas-y-descuentos'
  /ubl2.1/invoice?case=sendinvoice-testsetid-delivery:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-delivery'
  /ubl2.1/invoice?case=sendinvoice-testsetid-impuesto-licores:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-impuesto-licores'
  /ubl2.1/invoice?case=sendinvoice-testsetid-impuesto-bolsa:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-impuesto-bolsa'
  /ubl2.1/credit-note?case=sendcreditnote-testsetid-varias-lineas:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1credit-note?case=sendcreditnote-testsetid-varias-lineas'
  /ubl2.1/invoice?case=sendinvoice-testsetid-allowance-a-credito:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-allowance-a-credito'
  /ubl2.1/invoice?case=sendinvoice-testsetid-allowance-dos-invoice-lines:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-allowance-dos-invoice-lines'
  /ubl2.1/invoice?case=sendinvoiceprepaidpayment-testsetid:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoiceprepaidpayment-testsetid'
  /ubl2.1/invoice?case=sendinvoice-testsetid-charge:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-charge'
  /ubl2.1/invoice?case=sendinvoice-testsetid-charge-encabezado:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-charge-encabezado'
  /ubl2.1/invoice?case=sendinvoice-testsetid-articulos-con-dos-impuestos-telefonia-celular:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-articulos-con-dos-impuestos-telefonia-celular'
  /ubl2.1/invoice?case=sendinvoice-testsetid-articulos-con-impuesto-saludable-alimentos-ultraprocesados:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-articulos-con-impuesto-saludable-alimentos-ultraprocesados'
  /ubl2.1/invoice?case=sendinvoice-testsetid-articulos-con-impuesto-licores:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-articulos-con-impuesto-licores'
  /ubl2.1/invoice?case=sendinvoice-testsetid-articulos-con-impuesto-saludable-bebidas-azucaradas:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-articulos-con-impuesto-saludable-bebidas-azucaradas'
  /ubl2.1/invoice?case=sendinvoice-testsetid-articulos-con-impuesto-saludable-bebidas-azucaradas-varias:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-articulos-con-impuesto-saludable-bebidas-azucaradas-varias'
  /ubl2.1/invoice?case=sendinvoice-testsetid-productos-gratis:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-productos-gratis'
  /ubl2.1/invoice?case=sendinvoice-testsetid-dos-tarifas-impuestos-y-retenciones:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-dos-tarifas-impuestos-y-retenciones'
  /ubl2.1/invoice?case=sendinvoice-testsetid-impuesto-inc:
    $ref: './04-CasuisticasDeEnvios/04-casuisticas/casuisticas.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-impuesto-inc'
  /ubl2.1/invoice?case=sendinvoice-testsetid-consumidor-final:
    $ref: './05-ConsumidorFinal/05-consumidor-final/consumidor-final.yaml#/paths/~1ubl2.1~1invoice?case=sendinvoice-testsetid-consumidor-final'
  /api/information/89008003/1900-01-01/2023-09-15:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1information~189008003~11900-01-01~12023-09-15'
  /api/total_documents/89008003/1900-01-01/2023-09-15:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1total_documents~189008003~11900-01-01~12023-09-15'
  /information/89008003/page/0/page:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1information~189008003~1page~10~1page'
  /documents:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1documents'
  /api/ubl2.1/register-update-customer:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1register-update-customer'
  /customer/31/31999910:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1customer~131~131999910'
  /api/ubl2.1/certificate-end-date:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1certificate-end-date'
  /ubl2.1/next-consecutive:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1ubl2.1~1next-consecutive'
  /api/ubl2.1/xml/document/7735317bef9d6b648eeb0d0ad56ec5feb63911072947a3d06a894bf6dd66a3c912325660eeb27d7424d23af740432f66:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1xml~1document~17735317bef9d6b648eeb0d0ad56ec5feb63911072947a3d06a894bf6dd66a3c912325660eeb27d7424d23af740432f66'
  /api/ubl2.1/emailconfig:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1emailconfig'
  /api/ubl2.1/name-by-nit/89008003:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1name-by-nit~189008003'
  /api/ubl2.1/SearchCompany/1124024319:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1SearchCompany~11124024319'
  /api/ubl2.1/join-pdfs:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1join-pdfs'
  /api/ubl2.1/download/89008003/Attachment-SETP990000399.xml/BASE64:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1download~189008003~1Attachment-SETP990000399.xml~1BASE64'
  /api/ubl2.1/download/89008003/Attachment-SETP990000506.xml/BASE64:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1download~189008003~1Attachment-SETP990000506.xml~1BASE64'
  /api/invoice/89008003/FES-SETP990000650.pdf:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1invoice~189008003~1FES-SETP990000650.pdf'
  /api/receivedfile/89008003/ad090011631902722219520220419145805646.xml:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1receivedfile~189008003~1ad090011631902722219520220419145805646.xml'
  /api/ubl2.1/invoice/current_number/1:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1invoice~1current_number~11'
  /api/ubl2.1/delete/company/89008003/2:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1delete~1company~189008003~12'
  /api/send-email-customer/NO:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1send-email-customer~1NO'
  /api/ubl2.1/send-email:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1send-email'
  /api/send-email-employee/NO:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1send-email-employee~1NO'
  /api/ubl2.1/config/logo:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1config~1logo'
  /api/ubl2.1/certificates-listing/89008003:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1certificates-listing~189008003'
  /api/ubl2.1/config/generateddocuments:
    $ref: './06-Utilidades/06-utilidades/utilities.yaml#/paths/~1api~1ubl2.1~1config~1generateddocuments'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
