openapi: 3.0.0
info:
  title: Factura Electrónica
  version: 1.0.0
servers:
  - url: https://{url_base}/api
    variables:
      url_base:
        default: buho.fastura.uio.la
        description: Base URL of the API

paths:
  /ubl2.1/invoice:
    post:
      summary: Enviar Factura (Síncrono)
      description: |
        Envía una factura electrónica de venta de manera síncrona.
        
        - Requiere un token de autorización.
        - La respuesta incluye el estado de validación de la DIAN.
        - No afecta el set de pruebas si se usa el parámetro de testSetId.
      tags:
        - Factura
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: './invoice-component.yaml#/components/schemas/InvoiceGeneral'
                - $ref: './invoice-component.yaml#/components/schemas/InvoiceExportacion'
                - $ref: './invoice-component.yaml#/components/schemas/InvoiceContingencia'
                - $ref: './invoice-component.yaml#/components/schemas/InvoiceAIU'
            examples:
              General:
                summary: Factura General
                value:
                  number: 100
                  type_document_id: 1
                  date: "2020-09-22"
                  time: "06:00:00"
                  resolution_number: "18760000001"
                  prefix: "SETP"
                  notes: "ESTA ES UNA PRUEBA DE FACTURA"
                  sendmail: true
                  sendmailtome: true
                  customer:
                    identification_number: 900166483
                    dv: 1
                    name: "INVERSIONES DAVAL SAS"
                    phone: "3103891693"
                    address: "CLL 4 NRO 33-90"
                    email: "alexanderobandolondono@gmail.com"
                    merchant_registration: "0000000-00"
                    type_document_identification_id: 6
                    type_organization_id: 1
                    municipality_id: 822
                    type_regime_id: 1
                  payment_form:
                    payment_form_id: 1
                    payment_method_id: 10
                    payment_due_date: "2020-09-22"
                    duration_measure: "0"
                  legal_monetary_totals:
                    line_extension_amount: "840336.13"
                    tax_exclusive_amount: "840336.13"
                    tax_inclusive_amount: "1000000.00"
                    allowance_total_amount: "0.00"
                    charge_total_amount: "0.00"
                    payable_amount: "1000000.00"
                  tax_totals:
                    - tax_id: 1
                      tax_amount: "159663.87"
                      percent: "19"
                      taxable_amount: "840336.13"
                  invoice_lines:
                    - unit_measure_id: 70
                      invoiced_quantity: "1"
                      line_extension_amount: "840336.13"
                      free_of_charge_indicator: false
                      tax_totals:
                        - tax_id: 1
                          tax_amount: "159663.87"
                          taxable_amount: "840336.13"
                          percent: "19.00"
                      description: "COMISION POR SERVICIOS"
                      notes: "ESTA ES UNA PRUEBA DE NOTA DE DETALLE DE LINEA."
                      code: "COMISION"
                      type_item_identification_id: 4
                      price_amount: "1000000.00"
                      base_quantity: "1"
      responses:
        '200':
          description: Factura procesada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
                  ResponseDian:
                    type: object
                  zipinvoicexml:
                    type: string
        '422':
          description: Error de validación

  /ubl2.1/invoice/{testSetId}:
    post:
      summary: Enviar Factura (Set de Pruebas / Asíncrono)
      description: |
        Envía una factura impactando un Set de Pruebas específico.
        
        - **Modo Asíncrono**: Este endpoint se usa típicamente para habilitación.
        - La respuesta incluye un `ZIP_KEY` que debe ser consultado posteriormente.
      tags:
        - Factura
      parameters:
        - in: path
          name: testSetId
          schema:
            type: string
          required: true
          description: ID del Set de Pruebas entregado por la DIAN.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './invoice-component.yaml#/components/schemas/InvoiceGeneral'
      responses:
        '200':
          description: Factura enviada a set de pruebas
          content:
            application/json:
              schema:
                type: object
                properties:
                  zipKey:
                    type: string
                    description: Clave para consultar el estado del envío asíncrono
